In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

In [3]:
from src.eda import explore_features

# Exploratory Data Analysis

In [5]:
dataset = pd.read_csv("data/pf_suvs.csv")

In [6]:
for column in dataset.columns:
    print(column)

Unnamed: 0
Marca
Modelo
Año
Versión
Color
Tipo de combustible
Puertas
Transmisión
Motor
Tipo de carrocería
Con cámara de retroceso
Kilómetros
Título
Precio
Moneda
Descripción
Tipo de vendedor

In [7]:
TARGET = "Precio"

X = dataset.drop(columns = [TARGET])
y = dataset[TARGET]

### Features Analysis

In [11]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 180)

In [12]:
# Explore Dataset Features
feature_summary = explore_features(X)

display(feature_summary["numeric"])
display(feature_summary["categorical"])

   feature    dtype  non_missing  missing  missing_%     min       max         mean  median          std      q1      q3  zero_count  outlier_count  outlier_%  unique  unique_%
0      Año  float64        18254        0        0.0  1981.0  436694.0  2042.796209  2019.0  3217.260996  2016.0  2024.0           0            260       1.42      40      0.22
1  Puertas  float64        18254        0        0.0     2.0   60252.0    18.167306     5.0   891.766121     5.0     5.0           0            523       2.87       7      0.04

,feature,dtype,categories_preview,most_frequent,most_frequent_count,most_frequent_%,least_frequent_preview,rare_categories,missing,missing_%,non_missing,unique,unique_%
0,Marca,str,Ford: 2161 | Jeep: 2050 | Volkswagen: 2037 | Chevrolet: 1750 | Renault: 1491,Ford,2161,11.84,Range Rover: 1 | Rrenault: 1 | Jetur: 1 | hiunday: 1 | Vol: 1,5,0,0.00,18254,47,0.26
1,Modelo,str,Ecosport: 1569 | Tracker: 1511 | 2008: 1144 | Duster: 1048 | Compass: 916,Ecosport,1569,8.60,Tiggo 8 Pro: 2 | Clase GL: 2 | DS3: 2 | Mohave: 2 | F-PACE: 2,0,0,0.00,18254,137,0.75
2,Versión,str,1.6 Exclusive Cvt: 320 | 1.4 250 Tsi Comfortline: 261 | 1.4 250 Tsi Highline: 255 | 1.8 Ltz+ Awd At 140cv: 213 | 1.2...,1.6 Exclusive Cvt,320,1.75,2.0 Hse 4 At: 1 | 2.7 4WD V6: 1 | 2.0 GLC300 4MATIC COUPE AMG-LINE: 1 | 1.8 Awd Ltz At: 1 | Trendline 200 Tsi Automa...,1038,0,0.00,18254,2072,11.35
3,Color,str,Gris: 5468 | Blanco: 4809 | Negro: 2825 | Plateado: 1427 | Azul: 1121,Gris,5468,29.96,GRIS SILVERSTONE: 1 | GRANITE CRYSTA BC: 1 | SKYSCRAPER GRAU METALLIC: 1 | BLANCO BANCHISA BICOLOR NEGRO: 1 | GRIS P...,32,389,2.13,17865,70,0.38
4,Tipo de combustible,str,Nafta: 16067 | Diésel: 1328 | Nafta/GNC: 451 | Híbrido/Nafta: 269 | Híbrido: 105,Nafta,16067,88.02,Mild Hybrid: 10 | Eléctrico: 12 | GNC: 12 | Híbrido: 105 | Híbrido/Nafta: 269,0,0,0.00,18254,8,0.04
5,Transmisión,str,Automática: 12281 | Manual: 5834 | Automática secuencial: 123 | Semiautomática: 1,Automática,12281,67.28,Semiautomática: 1 | Automática secuencial: 123 | Manual: 5834 | Automática: 12281,1,15,0.08,18239,4,0.02
6,Motor,str,1.6: 4132 | 2.0: 3121 | 1.8: 1749 | 1.0: 1417 | 1.3: 1079,1.6,4132,22.64,T270 1.3T: 1 | Nafta / Electrico: 1 | 1.5turbo: 1 | 3.0 biturbo 440cv: 1 | 2.5 Híbrido: 1,159,38,0.21,18216,271,1.48
7,Tipo de carrocería,str,SUV: 18254,SUV,18254,100.00,SUV: 18254,0,0,0.00,18254,1,0.01
8,Con cámara de retroceso,str,Sí: 3731 | No: 960,Sí,3731,20.44,No: 960 | Sí: 3731,0,13563,74.30,4691,2,0.01
9,Kilómetros,str,0.0: 4237 | 0 km: 324 | 1000.0: 220 | 90000.0: 194 | 120000.0: 194,0.0,4237,23.21,54.000 km: 1 | 63.000 km: 1 | 83.000 km: 1 | 60.000 km: 1 | 40.000 km: 1,1362,0,0.00,18254,2175,11.92
10,Título,str,Nissan Kicks 1.6 Exclusive Cvt: 320 | Volkswagen Taos 1.4 250 Tsi Comfortline: 261 | Volkswagen Taos 1.4 250 Tsi Hig...,Nissan Kicks 1.6 Exclusive Cvt,320,1.75,Land Rover Freelander 2.0 Hse 4 At: 1 | Hyundai Santa Fe: 1 | Mercedes-Benz Clase GLC 2.0 GLC300 4MATIC COUPE AMG-LI...,1168,0,0.00,18254,2220,12.16
11,Moneda,str,$: 11158 | US$: 7096,$,11158,61.13,US$: 7096 | $: 11158,0,0,0.00,18254,2,0.01
12,Descripción,str,El vendedor no incluyó una descripción del producto: 2260 | La tienda no incluyó una descripción del producto: 62 | ...,El vendedor no incluyó una descripción del producto,2260,12.38,EXCELENTE ESTADO (igual a 0km)Único dueñoListo para transferir y disfrutarLibre de deudasActualmente en garantía de ...,10662,0,0.00,18254,12142,66.52
13,Tipo de vendedor,str,concesionaria: 8509 | particular: 5676 | tienda: 4069,concesionaria,8509,46.61,tienda: 4069 | particular: 5676 | concesionaria: 8509,0,0,0.00,18254,3,0.02