<h3 style="background-color: #343a40; color: #ffffff; display: inline-block; padding: 6px 10px; border-radius: 6px;">
Preprocesamiento de las features
</h3>

<div style="
    text-align: center;
    background-color: rgba(0, 0, 0, 0.3);
    color: white;
    padding: 10px;
    border-radius: 8px;
    font-weight: bold;
">
Limpieza y validación de la variable precio
</div>

In [2]:
import pandas as pd

In [13]:
%load_ext autoreload
%autoreload 2

import src.eda as eda

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
dataset = pd.read_csv("data/pf_suvs.csv")

<h1 style="
    background-color: #d0ebff; 
    color: #1a1a1a; 
    display: inline-block; 
    padding: 10px 18px; 
    border-radius: 10px;
    font-size: 32px;
">
Exploratory Data Analysis
</h1>

In [5]:
for column in dataset.columns:
    print(column)

Unnamed: 0
Marca
Modelo
Año
Versión
Color
Tipo de combustible
Puertas
Transmisión
Motor
Tipo de carrocería
Con cámara de retroceso
Kilómetros
Título
Precio
Moneda
Descripción
Tipo de vendedor

In [6]:
TARGET = "Precio"

X = dataset.drop(columns = [TARGET])
y = dataset[TARGET]

In [7]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 180)

<h3 style="background-color: #343a40; color: #ffffff; display: inline-block; padding: 6px 10px; border-radius: 6px;">
Label Analysis
</h3>

In [15]:
target_summary = eda.explore_target(y, currency=X["Moneda"])
display(target_summary)

  group  count  missing  missing_%       min          q1      median          mean          q3          max           std  zero_count
0   All  18254        0        0.0     111.0     31900.0  17200000.0  1.760162e+07  29950000.0  349500000.0  1.720810e+07           0
1     $  11158        0        0.0  119000.0  19000000.0  27320000.0  2.877461e+07  35900000.0  349500000.0  1.277861e+07           0
2   US$   7096        0        0.0     111.0     16000.0     24000.0  3.281019e+04     38900.0     610000.0  2.885445e+04           0

<h3 style="background-color: #343a40; color: #ffffff; display: inline-block; padding: 6px 10px; border-radius: 6px;">
Feature Analysis
</h3>

In [ ]:
# Explore Dataset Features
feature_summary = eda.explore_features(X)

display(feature_summary["numeric"])
display(feature_summary["categorical"])

   feature    dtype  non_missing  missing  missing_%     min       max         mean  median          std      q1      q3  zero_count  outlier_count  outlier_%  unique  unique_%
0      Año  float64        18254        0        0.0  1981.0  436694.0  2042.796209  2019.0  3217.260996  2016.0  2024.0           0            260       1.42      40      0.22
1  Puertas  float64        18254        0        0.0     2.0   60252.0    18.167306     5.0   891.766121     5.0     5.0           0            523       2.87       7      0.04

,feature,dtype,categories_preview,most_frequent,most_frequent_count,most_frequent_%,least_frequent_preview,rare_categories,missing,missing_%,non_missing,unique,unique_%
0,Marca,object,Ford: 2161 | Jeep: 2050 | Volkswagen: 2037 | Chevrolet: 1750 | Renault: 1491,Ford,2161,11.84,Range Rover: 1 | Rrenault: 1 | Jetur: 1 | hiunday: 1 | Vol: 1,5,0,0.00,18254,47,0.26
1,Modelo,object,Ecosport: 1569 | Tracker: 1511 | 2008: 1144 | Duster: 1048 | Compass: 916,Ecosport,1569,8.60,Nativa: 2 | Defender: 2 | 208: 2 | C4 Aircross: 2 | F-PACE: 2,0,0,0.00,18254,137,0.75
2,Versión,object,1.6 Exclusive Cvt: 320 | 1.4 250 Tsi Comfortline: 261 | 1.4 250 Tsi Highline: 255 | 1.8 Ltz+ Awd At 140cv: 213 | 1.2...,1.6 Exclusive Cvt,320,1.75,1.6 Exclusive: 1 | TITANIUM 2.0L AT POWE: 1 | SV V8: 1 | 1.6 Gl Plus Allgrip 120cv: 1 | Trendline 200 Tsi Automatica...,1038,0,0.00,18254,2072,11.35
3,Color,object,Gris: 5468 | Blanco: 4809 | Negro: 2825 | Plateado: 1427 | Azul: 1121,Gris,5468,29.96,GRAY: 1 | Blanco Glaciar: 1 | GRIS ARTENSE: 1 | Cobre: 1 | ROJO SUNSET METALIZADO: 1,32,389,2.13,17865,70,0.38
4,Tipo de combustible,object,Nafta: 16067 | Diésel: 1328 | Nafta/GNC: 451 | Híbrido/Nafta: 269 | Híbrido: 105,Nafta,16067,88.02,Mild Hybrid: 10 | GNC: 12 | Eléctrico: 12 | Híbrido: 105 | Híbrido/Nafta: 269,0,0,0.00,18254,8,0.04
5,Transmisión,object,Automática: 12281 | Manual: 5834 | Automática secuencial: 123 | Semiautomática: 1,Automática,12281,67.28,Semiautomática: 1 | Automática secuencial: 123 | Manual: 5834 | Automática: 12281,1,15,0.08,18239,4,0.02
6,Motor,object,1.6: 4132 | 2.0: 3121 | 1.8: 1749 | 1.0: 1417 | 1.3: 1079,1.6,4132,22.64,45 TFSI 2.0 245cv: 1 | 1.3 Turbo AT9: 1 | 1.6 16 v: 1 | v8 4.4: 1 | 2.5 Híbrido: 1,159,38,0.21,18216,271,1.48
7,Tipo de carrocería,object,SUV: 18254,SUV,18254,100.00,SUV: 18254,0,0,0.00,18254,1,0.01
8,Con cámara de retroceso,object,Sí: 3731 | No: 960,Sí,3731,20.44,No: 960 | Sí: 3731,0,13563,74.30,4691,2,0.01
9,Kilómetros,object,0.0: 4237 | 0 km: 324 | 1000.0: 220 | 120000.0: 194 | 90000.0: 194,0.0,4237,23.21,43242.0: 1 | 168500.0: 1 | 60215.0: 1 | 71305.0: 1 | 29350.0: 1,1362,0,0.00,18254,2175,11.92
10,Título,object,Nissan Kicks 1.6 Exclusive Cvt: 320 | Volkswagen Taos 1.4 250 Tsi Comfortline: 261 | Volkswagen Taos 1.4 250 Tsi Hig...,Nissan Kicks 1.6 Exclusive Cvt,320,1.75,Volkswagen T-Cross highline bitono: 1 | Toyota Corolla Cross Seg 1.8 HIBRIDA: 1 | Suzuki Grand Vitara 4x4 2.0 Tdi Ma...,1168,0,0.00,18254,2220,12.16
11,Moneda,object,$: 11158 | US$: 7096,$,11158,61.13,US$: 7096 | $: 11158,0,0,0.00,18254,2,0.01
12,Descripción,object,El vendedor no incluyó una descripción del producto: 2260 | La tienda no incluyó una descripción del producto: 62 | ...,El vendedor no incluyó una descripción del producto,2260,12.38,Concesionario Peugeot OficialPeugeot 2008 GT 2025Retira con tu anticipo y el resto en cuotas de $370.000Tomamos tu u...,10662,0,0.00,18254,12142,66.52
13,Tipo de vendedor,object,concesionaria: 8509 | particular: 5676 | tienda: 4069,concesionaria,8509,46.61,tienda: 4069 | particular: 5676 | concesionaria: 8509,0,0,0.00,18254,3,0.02

In [ ]:
print(f"Outlier de año más grande: {(dataset["Año"]).max()}")
print(f"Cantidad de años mayores al año actual: {(dataset["Año"] > 2026).sum()}")

Outlier de año más grande: 436694.0
Cantidad de años mayores al año actual: 1

Con esto detectamos que hay un valor incoherente de la feature Año, por lo que se deicde eliminar la muestra con ese dato del dataset